permalink: /:year-:month-:day/:title/
plugins: [jekyll-paginate]
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  extensions:
    - autolink
    - footnotes
    - smart
  use_coderay: true
  syntax_highlighter: rouge
  coderay:
    coderay_line_numbers:  inline


paginate: 10
paginate_path: ":num"
baseurl: ""



defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      styles : [highlight.css,post.css]
      scripts : [post.js]



title: "suimi"
email:
description: "现在也不晚"
github_username:  "suimi"
disqus_shortname: "suimi"



url: "http://suimi.github.io"
imgrepo: "http://suimi.github.io/static/img"

